### ISSUE TITLE
error - InventoryClickEvent

### ISSUE THREAD

**Issue by mat41997** [ty2u/spawner#16]
logs
http://pastebin.com/xScV4EW1

timings
https://timings.aikar.co/v2/?id=1a36fde835914d629f355d835a8d2982

**Comment by ty2u** [comment]
Thanks for the report! I will see what I can do about that but I've never tested it on Paper Spigot. Will look through their patches and see what's up.

**Comment by ty2u** [comment]
I thought I replied to this a few hours ago saying that I pushed a fix which hopefully fixes that. Maybe I accidentally replied to something else haha

Will compile and release a new version once I fix some other little issue I found when I try to use a firework spawner.
