### ISSUE TITLE
frequency don't work on 1.10

### ISSUE THREAD

**Issue by xXandrescolXx** [ty2u/spawner#17]
Hello!!

The spawn frequency don't change on Spawner Plugin version 2.7 and 2.6 for minecraft 1.10,  always the mobs spawn one constantly (it is very slowly). I set the frequency in config.yml but always it's the same spawning.

**Comment by ty2u** [comment]
Hi there,

Thanks for the report. I will look into it and release a fix if necessary in the next couple days.

**Comment by ty2u** [comment]
Fixed this and released a new version.

**Comment by xXandrescolXx** [comment]
Yes, thanks for fix it :D
