### ISSUE TITLE
1.11 Mobs

### ISSUE THREAD

**Issue by CeIebrimbor** [ty2u/spawner#18]
02.12 18:55:49 [Server] ERROR Could not pass event SpawnerSpawnEvent to Spawner v2.5-0622a49
02.12 18:55:49 [Server] INFO org.bukkit.event.EventException
02.12 18:55:49 [Server] INFO at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callSpawnerSpawnEvent(CraftEventFactory.java:1042) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:116) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.TileEntityMobSpawner.F_(SourceFile:91) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1621) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:638) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:885) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
02.12 18:55:49 [Server] INFO Caused by: java.lang.IllegalArgumentException: No enum constant me.ryvix.spawner.SpawnerType.VINDICATOR
02.12 18:55:49 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_102]
02.12 18:55:49 [Server] INFO at me.ryvix.spawner.SpawnerType.valueOf(SpawnerType.java:40) ~[?:?]
02.12 18:55:49 [Server] INFO at me.ryvix.spawner.SpawnerType.getUnformattedTextFromName(SpawnerType.java:242) ~[?:?]
02.12 18:55:49 [Server] INFO at me.ryvix.spawner.SpawnerEvents.onSpawnerSpawn(SpawnerEvents.java:426) ~[?:?]
02.12 18:55:49 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
02.12 18:55:49 [Server] INFO at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.jar:git-Paper-956]
02.12 18:55:49 [Server] INFO ... 14 more

**Comment by ty2u** [comment]
This is caused by 1.11 adding new mob types. In this case it looks like VINDICATOR. VINDICATOR will be added in the next release which should be soon.
