### ISSUE TITLE
protect_from_explosions boolean failure

### ISSUE THREAD

**Issue by tspringst33n** [ty2u/spawner#3]
In the lines below you forgot to add an == true and == false to the expressions.
```java
if (Main.instance.config.getBoolean("protect_from_explosions")) 
and
else if (Main.instance.config.getBoolean("drop_from_explosions")) 
```

This results in the spawner not being dropped no matter what the setting is. The correct code is below
```java
if (Main.instance.config.getBoolean("protect_from_explosions") == true) {
else if (Main.instance.config.getBoolean("drop_from_explosions") == true) {
```

**Comment by ty2u** [comment]
Just tested and it seems to work ok to me the way it is. In fact, when you say if (true) then it is the same as saying if (true == true)
