### ISSUE TITLE
cannot break the speaner with perm in the file

### ISSUE THREAD

**Issue by Lokiro67** [ty2u/spawner#31]
i have put the perm in my default group and vip but annot place and break spawner only can in OP mod

**Comment by ty2u** [comment]
Hello,

What version of Spigot are you using?

What version of the Spawner plugin are you using?

What permissions plugin are you using?

What permissions have you added?

Do you see any errors in your logs when you start the server?

**Comment by Lokiro67** [comment]
its solved its my fault my map restricted this x)
