### ISSUE TITLE
Request for GriefPrevention & WorldGuard protection support

### ISSUE THREAD

**Issue by solidern** [ty2u/spawner#5]
Hi Developer
Please, add support bypass for GriefPrevention and WordGuard flags. If it is possible.
I want to be functional even in protected areas.
Very thanks

**Comment by ty2u** [comment]
Hello,
I'm not entirely sure what you're asking. Are you saying spawners don't work with GriefPrevention and WorldGuard or are you saying you want people to be able to break them even in those protected areas? Please explain in more detail.
