### ISSUE TITLE
Default spawner

### ISSUE THREAD

**Issue by James18plays** [ty2u/spawner#6]
Is there a way to make spawners stop going to a pig spawner?

**Comment by ty2u** [comment]
They shouldn't be doing that. Make sure you are using the proper version of spigot the plugin was built against. If you are using a later version of spigot let me know, I may have to rebuild a new version against it.

**Comment by James18plays** [comment]
Whats spigot?

**Comment by James18plays** [comment]
Im using 2.4 for 1.8

**Comment by James18plays** [comment]
Should i try going to Spawner-2.3 for 1.8?

**Comment by James18plays** [comment]
@ty2u Still having the same problem

**Comment by ty2u** [comment]
Spigot is the software that powers the server. Are you using Spigot rather than Bukkit or other server software?

Yes Spawner 2.4 worked fine on Spigot 1.8.

If you are having issues with pigs then do you see any errors in your server log the first time you place a spawner or try to spawn something after the server starts?

Are you using any other plugins which might conflict? Have you tested with no plugins on a test server?

**Comment by James18plays** [comment]
@ty2u I have not. And We are using Bukkit. And they work fine for the most part but when you place it it says "Placing default spawner (either this spawner is invalid or disabled)" i havent messed with config. everything is enabled. and if i do /spawer {entity} and change the spawner then mine it with silktouch its fine for the most part kinda. sometimes it messes up

**Comment by James18plays** [comment]
I also dont believe any of our plugins would conflict with it

**Comment by James18plays** [comment]
The only plugin what i think would have anything to do with it would be SilkSpawners

**Comment by James18plays** [comment]
We just switch back to spigot and its working fine so far.

**Comment by James18plays** [comment]
any suggestions with For bukkit?

**Comment by ty2u** [comment]
I doubt you can use SilkSpawners and this plugin at the same time. Use one or the other. This plugin is coded for Spigot and requires it. As far as I know there is no Bukkit or CraftBukkit anymore.

**Comment by James18plays** [comment]
Okay thank you for your time.
